extern double matrix[2][50];
void open();
void print_arr ();
void balance(int num_account);
void deposit_account(int num_account, double amount);
void attratction(int num_account, double amount);
void close(int num_account);
void interest();
void print_all_open_acuont();
void close_all_counts();
